### ISSUE TITLE
Question: What's the advantage(s) over functools.lru_cache?

### ISSUE THREAD

**Issue by waynew** [atmb4u/cashier#1]
What it says on the tin - are you just on a version of Python where lru_cache isn't available?

**Comment by atmb4u** [comment]
`lru_cache`, though a standard on distribution, is _not persistent_ - This cache will persist in between multiple runs.
Fair question, though.
Planning to make it have multiple backends other than SQLite3, like `flat file`, `memory`, `redis` and so on - to make this a `superset of caching`.

**Comment by waynew** [comment]
You may want to add a " why not lru_cache" to your readme, for other folks like me :)
